//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCV
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Experience
    {
        public int Id { get; set; }
        public int cvId { get; set; }
        [Required(ErrorMessage = "Company name is required.")]
        public string company_name { get; set; }
        public string title { get; set; }
        [Required(ErrorMessage = "Period is required.")]
        public string period { get; set; }
        public string description { get; set; }
    
        public virtual CvMaster CvMaster { get; set; }
    }
}
