//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineCVEntities : DbContext
    {
        public OnlineCVEntities()
            : base("name=OnlineCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CvMaster> CvMasters { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Expertise> Expertises { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
    }
}
